openapi: 3.0.3
info:
  title: Basic_NoVersioning
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:5129'
paths:
  /Company/SetCompanyName:
    put:
      tags:
        - Company
      operationId: SetCompanyName
      description: Set company name and swagger returns it
      parameters:
        - in: query
          name: companyName
          description: set company name
          required: true
          schema:
            type: string
      responses:
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: string
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                type: string
  /Company/SetCompanyName20240100:
    put:
      tags:
        - Company
      operationId: SetCompanyName20240100
      summary: introduced in version 20240100
      description: Set company name and swagger returns it
      parameters:
        - in: query
          name: companyName
          description: set company name
          required: true
          schema:
            type: string
        - in: query
          name: companyRegion
          description: set region where company is based
          required: true
          schema:
            type: string
      responses:
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: string
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                type: string
  /Company/ReadCompanyInfo:
    get:
      tags:
        - "Company"
      summary: default version
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Company"
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
            text/json:
              schema:
                $ref: "#/components/schemas/Company"
  /Company/ReadCompanyInfo20240100:
    get:
      tags:
        - Company
      summary: introduced in version 20240100
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Company20240100"
            application/json:
              schema:
                $ref: "#/components/schemas/Company20240100"
            text/json:
              schema:
                $ref: "#/components/schemas/Company20240100"
components:
  schemas:
    Company20240100:
      description: version 20240100
      type: object
      properties:
        name:
          type: "string"
          nullable: true
        city:
          type: "string"
          nullable: true
        region:
          type: string
          nullable: true
    Company:
      type: "object"
      properties:
        name:
          type: "string"
          nullable: true
        city:
          type: "string"
          nullable: true
      additionalProperties: false
